apiVersion: v1
kind: Service
metadata:
  name: k8-service
spec:
  type: NodePort
  selector:
    app: nginx-rs
  ports:
    - name: http
      nodePort: 30500
      port: 81
      protocol: TCP
      targetPort: 81
